name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Firebase Tools
        run: npm install -g firebase-tools

      - name: Criar chave Firebase
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json

      - name: Deploy Firebase
        run: firebase deploy --only hosting,firestore:rules --project bolaodolobo-e867e
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json